# Auto-generated openkrill module fragment for external-secrets
# Generated from CRD specification. See specs/nix-module-crds.md.
# This is a fragment — import from a composing module that declares
# enable, extraManifests, and other shared options.
{ config, lib, ... }:
with lib;
let
  cfg = config.openkrill.apps."external-secrets";
  compact = filterAttrs (_: v: v != null);
  AuthBasicModule = types.submodule {
    options = {
      "password" = mkOption {
        description = "A basic auth password used to authenticate against the Grafana instance.";
        type = AuthBasicPasswordModule;
      };
      "username" = mkOption {
        description = "A basic auth username used to authenticate against the Grafana instance.";
        type = types.str;
      };
    };
  };
  mkAuthBasic = res: {
    "password" = mkAuthBasicPassword res."password";
    inherit (res) "username";
  };
  AuthBasicPasswordModule = types.submodule {
    options = {
      "key" = mkOption {
        description = "The key where the token is found.";
        type = (types.nullOr types.str);
        default = null;
      };
      "name" = mkOption {
        description = "The name of the Secret resource being referred to.";
        type = (types.nullOr types.str);
        default = null;
      };
    };
  };
  mkAuthBasicPassword =
    res:
    {
    }
    // optionalAttrs (res."key" != null) { inherit (res) "key"; }
    // {
    }
    // optionalAttrs (res."name" != null) { inherit (res) "name"; }
    // {
    };
  AuthModule = types.submodule {
    options = {
      "basic" = mkOption {
        description = "Basic auth credentials used to authenticate against the Grafana instance.\nNote: you need a token which has elevated permissions to create service accounts.\nSee here for the documentation on basic roles offered by Grafana:\nhttps://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/";
        type = (types.nullOr AuthBasicModule);
        default = null;
      };
      "token" = mkOption {
        description = "A service account token used to authenticate against the Grafana instance.\nNote: you need a token which has elevated permissions to create service accounts.\nSee here for the documentation on basic roles offered by Grafana:\nhttps://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/";
        type = (types.nullOr AuthTokenModule);
        default = null;
      };
    };
  };
  mkAuth =
    res:
    {
    }
    // optionalAttrs (res."basic" != null) { "basic" = mkAuthBasic res."basic"; }
    // {
    }
    // optionalAttrs (res."token" != null) { "token" = mkAuthToken res."token"; }
    // {
    };
  AuthTokenModule = types.submodule {
    options = {
      "key" = mkOption {
        description = "The key where the token is found.";
        type = (types.nullOr types.str);
        default = null;
      };
      "name" = mkOption {
        description = "The name of the Secret resource being referred to.";
        type = (types.nullOr types.str);
        default = null;
      };
    };
  };
  mkAuthToken =
    res:
    {
    }
    // optionalAttrs (res."key" != null) { inherit (res) "key"; }
    // {
    }
    // optionalAttrs (res."name" != null) { inherit (res) "name"; }
    // {
    };
  ServiceAccountModule = types.submodule {
    options = {
      "name" = mkOption {
        description = "Name is the name of the service account that will be created by ESO.";
        type = types.str;
      };
      "role" = mkOption {
        description = "Role is the role of the service account.\nSee here for the documentation on basic roles offered by Grafana:\nhttps://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/";
        type = types.str;
      };
    };
  };
  mkServiceAccount = res: {
    inherit (res) "name";
    inherit (res) "role";
  };
  GrafanasModule = types.submodule (
    { name, ... }:
    {
      options = {
        "namespace" = mkOption {
          type = types.str;
          description = "Namespace for this Grafana resource.";
        };
        "auth" = mkOption {
          description = "Auth is the authentication configuration to authenticate\nagainst the Grafana instance.";
          type = AuthModule;
        };
        "serviceAccount" = mkOption {
          description = "ServiceAccount is the configuration for the service account that\nis supposed to be generated by the generator.";
          type = ServiceAccountModule;
        };
        "url" = mkOption {
          description = "URL is the URL of the Grafana instance.";
          type = types.str;
        };
      };
    }
  );
  mkGrafana = name: res: {
    apiVersion = "generators.external-secrets.io/v1alpha1";
    kind = "Grafana";
    metadata = {
      inherit name;
      namespace = res.namespace;
    };
    spec = {
      "auth" = mkAuth res."auth";
      "serviceAccount" = mkServiceAccount res."serviceAccount";
      inherit (res) "url";
    };
  };
  allResources = (mapAttrsToList mkGrafana cfg."grafanas");
in
{
  options.openkrill.apps."external-secrets" = {
    "grafanas" = mkOption {
      type = types.attrsOf GrafanasModule;
      default = { };
      description = "Grafana CRD instances.";
    };
  };
  config = mkIf cfg.enable {
    openkrill.manifests."external-secrets".content = allResources;
  };
}
