# Auto-generated openkrill module fragment for flux
# Generated from CRD specification. See specs/nix-module-crds.md.
# This is a fragment — import from a composing module that declares
# enable, extraManifests, and other shared options.
{ config, lib, ... }:
with lib;
let
  cfg = config.openkrill.apps."flux";
  compact = filterAttrs (_: v: v != null);
  EventSourceModule = types.submodule {
    options = {
      "apiVersion" = mkOption {
        description = "API version of the referent";
        type = (types.nullOr types.str);
        default = null;
      };
      "kind" = mkOption {
        description = "Kind of the referent";
        type = (
          types.enum [
            "Bucket"
            "GitRepository"
            "Kustomization"
            "HelmRelease"
            "HelmChart"
            "HelmRepository"
            "ImageRepository"
            "ImagePolicy"
            "ImageUpdateAutomation"
            "OCIRepository"
          ]
        );
      };
      "matchLabels" = mkOption {
        description = "MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is \"key\", the\noperator is \"In\", and the values array contains only \"value\". The requirements are ANDed.\nMatchLabels requires the name to be set to `*`.";
        type = (types.attrsOf types.str);
        default = { };
      };
      "name" = mkOption {
        description = "Name of the referent\nIf multiple resources are targeted `*` may be set.";
        type = types.str;
      };
      "namespace" = mkOption {
        description = "Namespace of the referent";
        type = (types.nullOr types.str);
        default = null;
      };
    };
  };
  mkEventSource =
    res:
    {
    }
    // optionalAttrs (res."apiVersion" != null) { inherit (res) "apiVersion"; }
    // {
      inherit (res) "kind";
    }
    // optionalAttrs (res."matchLabels" != { }) { inherit (res) "matchLabels"; }
    // {
      inherit (res) "name";
    }
    // optionalAttrs (res."namespace" != null) { inherit (res) "namespace"; }
    // {
    };
  ProviderRefModule = types.submodule {
    options = {
      "name" = mkOption {
        description = "Name of the referent.";
        type = types.str;
      };
    };
  };
  mkProviderRef = res: {
    inherit (res) "name";
  };
  AlertsModule = types.submodule (
    { name, ... }:
    {
      options = {
        "namespace" = mkOption {
          type = types.str;
          description = "Namespace for this Alert resource.";
        };
        "eventMetadata" = mkOption {
          description = "EventMetadata is an optional field for adding metadata to events dispatched by the\ncontroller. This can be used for enhancing the context of the event. If a field\nwould override one already present on the original event as generated by the emitter,\nthen the override doesn't happen, i.e. the original value is preserved, and an info\nlog is printed.";
          type = (types.attrsOf types.str);
          default = { };
        };
        "eventSeverity" = mkOption {
          description = "EventSeverity specifies how to filter events based on severity.\nIf set to 'info' no events will be filtered.";
          type = (
            types.nullOr (
              types.enum [
                "info"
                "error"
              ]
            )
          );
          default = "info";
        };
        "eventSources" = mkOption {
          description = "EventSources specifies how to filter events based\non the involved object kind, name and namespace.";
          type = (types.listOf EventSourceModule);
        };
        "exclusionList" = mkOption {
          description = "ExclusionList specifies a list of Golang regular expressions\nto be used for excluding messages.";
          type = (types.listOf types.str);
          default = [ ];
        };
        "inclusionList" = mkOption {
          description = "InclusionList specifies a list of Golang regular expressions\nto be used for including messages.";
          type = (types.listOf types.str);
          default = [ ];
        };
        "providerRef" = mkOption {
          description = "ProviderRef specifies which Provider this Alert should use.";
          type = ProviderRefModule;
        };
        "summary" = mkOption {
          description = "Summary holds a short description of the impact and affected cluster.\nDeprecated: Use EventMetadata instead.";
          type = (types.nullOr types.str);
          default = null;
        };
        "suspend" = mkOption {
          description = "Suspend tells the controller to suspend subsequent\nevents handling for this Alert.";
          type = types.bool;
          default = false;
        };
      };
    }
  );
  mkAlert = name: res: {
    apiVersion = "notification.toolkit.fluxcd.io/v1beta3";
    kind = "Alert";
    metadata = {
      inherit name;
      namespace = res.namespace;
    };
    spec = {
    }
    // optionalAttrs (res."eventMetadata" != { }) { inherit (res) "eventMetadata"; }
    // {
    }
    // optionalAttrs (res."eventSeverity" != null) { inherit (res) "eventSeverity"; }
    // {
      "eventSources" = map mkEventSource res."eventSources";
    }
    // optionalAttrs (res."exclusionList" != [ ]) { inherit (res) "exclusionList"; }
    // {
    }
    // optionalAttrs (res."inclusionList" != [ ]) { inherit (res) "inclusionList"; }
    // {
      "providerRef" = mkProviderRef res."providerRef";
    }
    // optionalAttrs (res."summary" != null) { inherit (res) "summary"; }
    // {
    }
    // optionalAttrs res."suspend" { inherit (res) "suspend"; }
    // {
    };
  };
  allResources = (mapAttrsToList mkAlert cfg."alerts");
in
{
  options.openkrill.apps."flux" = {
    "alerts" = mkOption {
      type = types.attrsOf AlertsModule;
      default = { };
      description = "Alert CRD instances.";
    };
  };
  config = mkIf cfg.enable {
    openkrill.manifests."flux".content = allResources;
  };
}
